server:
  port: 9091

spring:
  application:
    name: retail-platform-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/retail_auth_db
    username: postgres
    password: bachisai2012

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: AUTH
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
