server:
  port: 8083

spring:
  application:
    name: retail-appservices-payments

  datasource:
    url: jdbc:postgresql://localhost:5432/retail_payments_db
    username: postgres
    password: bachisai2012
